#+TITLE: Crates 2 - Puzzle Game

* About

~crates2~ is a WIP puzzle game. More information
is to be added.

*Please note that this is still Work In Progress.*

* Getting Started

Prerequisites:

At this stage: =Common Lisp= implementation (tested with SBCL), =Quicklisp= and =make=.

Get sources and build by issuing commands:

#+begin_src shell
git clone https://github.com/octaspire/crates2.git
cd crates2
make
#+end_src

If you haven't cloned into directory that is known
to Quicklisp, you can tell about it by linking
or copying file ~etc/crates2.conf~ to
~$HOME/.config/common-lisp/source-registry.conf.d/crates2.conf~.
But please note, that the path given in that file probably
has to be changed to match the location of the cloned directory
on your machine.

You can also build and run by issuing command:

#+begin_src shell
make run
#+end_src

To install and start playing from level 20:

#+begin_src shell
make install && make play level=20
#+end_src

** Platform Specific Notes

*** OpenBSD

To use crates2 in OpenBSD without Common Lisp REPL - i.e. by running the generated
=crates2= executable directly - the =crates2= executable must be first
copied into ~/usr/local/bin~. This is because of the ~W^X~ protection
that OpenBSD uses. Command ~make run~ does this automagically in =OpenBSD=,
if file ~/etc/doas.conf~ has lines:

#+begin_src shell
permit nopass USERNAME as root cmd /bin/cp args crates2-text /usr/local/bin/
permit nopass USERNAME as root cmd /bin/cp args crates2-charms /usr/local/bin/
#+end_src

where ~USERNAME~ is your username. If you are getting error message

#+begin_src shell
RWX mmap not supported, is the current filesystem mounted with wxallowed?
#+end_src

in OpenBSD, then copying the executable to ~/usr/local/bin~ should fix the issue.

* Development

GNU Emacs with slime, having crates2 loaded,
can be launched by issuing the following command:

#+begin_src shell
make slime
#+end_src

* License

#+begin_example
   Octaspire Crates 2 - Puzzle Game
   Copyright 2020, 2021 octaspire.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
#+end_example
